Added Item class
chanson02/SENG3340 pull request #26
Opened 2024-04-02 20:58 UTC by NoahBartell

Added a basic template for adding items

2024-04-02 21:01 UTC, chanson02 requested changes

2024-04-02 21:01 UTC, chanson02 commented on src/Item.py
> +}
Can you add these default stats and images? Along with anything else in the `assets` folder
```python
        weapons = [
            {"name": "sword", "image": "./assets/sword.jpg", "KEY": [20, 30, 10]},
            {"name": "spear", "image": "./assets/spear.jpg", "KEY": [30, 10, 20]},
        ]
        armor = [
            {"name": "shield", "image": "./assets/shield.jpg", "KEY": [30, 10, 20]},
            {"name": "gloves", "image": "./assets/gloves.jpg", "KEY": [10, 10, 10]},
        ]```

2024-04-02 21:20 UTC, chanson02 approved these changes

2024-04-04 21:06 UTC, MLHumphries approved these changes

2024-04-04 22:15 UTC, chanson02 requested changes

2024-04-04 22:15 UTC, chanson02 commented on src/Item.py
> +}
Now that we've make the game into a package, these will need to be updated, see [here](https://github.com/chanson02/DunwoodyDisaster/blob/45f61357e684e2417419c8be827babdf3e23ed76/dunwoody_disaster/views/fightScreen.py#L28).

2024-04-04 22:15 UTC, chanson02 commented on src/Item.py
> +        return self.name, self.stats
This should return `str` instead of `tuple[str]`

2024-04-05 18:55 UTC, chanson02 approved these changes

2024-04-05 19:00 UTC, merged