17 user interaction
chanson02/SENG3340 pull request #30
Opened 2024-04-05 20:42 UTC by chanson02

The user can now click on the items in their arsenal to add them to their selected attacks.

2024-04-09 13:09 UTC, MLHumphries requested changes
Naming is the main change needed. We'll need to talk about the meter thing today most likely.

2024-04-09 13:09 UTC, MLHumphries commented on dunwoody_disaster/CharacterFactory.py
> +        self.mech_meter = Meter(QColor(50, 50, 50), 100)
Depending on if we go with this version or the one in my PR...
-Naming convention ex. magicMeter
-Mechanical is now stamina

2024-04-09 13:09 UTC, MLHumphries commented on dunwoody_disaster/CharacterFactory.py
> +    def set_mechanical(self, mech: int):
-Naming again
-Mechanical should be Stamina.

2024-04-09 15:22 UTC, chanson02 commented on dunwoody_disaster/CharacterFactory.py
> +        self.mech_meter = Meter(QColor(50, 50, 50), 100)
What branch do we change mechanical to stamina? I was going to keep using mechanical until that was merged in to avoid conflicts.

2024-04-09 15:24 UTC, chanson02 commented on dunwoody_disaster/CharacterFactory.py
> +        self.mech_meter = Meter(QColor(50, 50, 50), 100)
I believe in yours the `meters` are a `dict[str, int]` where the values are the integer points. In this version the meters on the player object are actual `Meter` objects.

2024-04-09 15:40 UTC, chanson02 reviewed
Happy birthday!

2024-04-09 15:40 UTC, chanson02 commented on dunwoody_disaster/views/action_selector.py
> +        self.defense: Optional[dict] = None
Make these `Item`s instead of dictionaries.

2024-04-09 15:40 UTC, chanson02 commented on dunwoody_disaster/views/arsenal.py
> +            {"name": "gloves", "image": DD.ASSETS["gloves"], "KEY": [10, 10, 10]},
Make these `Item`s instead of dictionaries

2024-04-09 15:40 UTC, chanson02 commented on dunwoody_disaster/views/characterState.py
> +        self.setLayout(self.create_layout())
```suggestion
        self.setLayout(self.create_layout())
        return
```
Remove pointless function

2024-04-09 15:40 UTC, chanson02 commented on dunwoody_disaster/views/characterState.py
> +        mech = QLabel(f"Mechanical: {self.character.curMechanical}")
These will need to be object properties so that they may be updated.

2024-04-09 15:40 UTC, chanson02 commented on dunwoody_disaster/CharacterFactory.py
> +        self.health_meter.setPercentage(percentage)
This should also update the health value in the `CharacterState`, The same for magic and mechanical.

2024-04-09 15:40 UTC, chanson02 commented on dunwoody_disaster/views/characterState.py
> +        self.setLayout(self.create_layout())
Or maybe change the update_ui button to update the health, magic, and mechanical values?

2024-04-09 15:40 UTC, chanson02 commented on dunwoody_disaster/views/characterState.py
> +        layout.addWidget(self.character.health_meter, row, 1, 1, 2)
Actually, it might be easiest to attach a `health_label` to the `Character` and have everything update from `character.set_health`.

2024-04-09 15:40 UTC, chanson02 commented on dunwoody_disaster/__init__.py
> +    return QSpacerItem(0, height, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
```suggestion
def spacer(height: int) -> QSpacerItem:
    """
    Create an invisible vertical spacer to separate UI elements.
    """
    return QSpacerItem(0, height, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
```

2024-04-09 20:38 UTC, chanson02 commented
Implement QScrollArea into the arsenal.

2024-04-09 20:55 UTC, MLHumphries commented on dunwoody_disaster/CharacterFactory.py
> +        self.mech_meter = Meter(QColor(50, 50, 50), 100)
I see that now. Yes, you are correct to make it an object vs. how I have it. I will remove this bit from my push.

We don't currently have a branch to change mechanical to stamina. I can roll it into my current branch I suppose.

2024-04-09 21:46 UTC, chanson02 commented on dunwoody_disaster/CharacterFactory.py
> +        self.mech_meter = Meter(QColor(50, 50, 50), 100)
I merged your branch into mine and made the updates from `mechanical` to `stamina`, so we should be good to go.

2024-04-11 20:35 UTC, instMeyFTW approved these changes

2024-04-11 20:51 UTC, merged