Fight Sequence
chanson02/SENG3340 pull request #31
Opened 2024-04-05 21:48 UTC by MLHumphries

Added checks to see if players can attack, calculates attack damage (based on weapon damage vs. armor), and reduces player/enemy health and stamina.

2024-04-06 03:40 UTC, chanson02 requested changes
Typehints and a couple simplifications

2024-04-06 03:40 UTC, chanson02 commented on dunwoody_disaster/CharacterFactory.py
> +        self.maxStamina = 0
I wonder how many problems this is going to cause...

2024-04-06 03:40 UTC, chanson02 commented on FightSequence.py
> +    def Fight(self, playerWeapon, enemyWeapon):
```suggestion
    def Fight(self, playerWeapon: Item.Weapon, enemyWeapon: Item.Weapon) -> tuple:
```

2024-04-06 03:40 UTC, chanson02 commented on FightSequence.py
> +    def CanAttack(self, player, attack) -> bool:
```suggestion
    def CanAttack(self, player: CharacterFactory.Character, attack: Item.Weapon) -> bool:
```

2024-04-06 03:40 UTC, chanson02 commented on FightSequence.py
> +        Checks to see if character has enough stamina or magic to attack with.
Good work on the docstrings! Keep it up!

2024-04-06 03:40 UTC, chanson02 commented on FightSequence.py
> +            return False
```suggestion
        return player.curStamina - attack.staminaCost >= 0 and player.curMagic >= attack.magicCost
```

2024-04-06 03:40 UTC, chanson02 commented on FightSequence.py
> +        return attackDamage
```suggestion
        return playerAttack.damage - targetDefense.armorVal
```

2024-04-06 03:40 UTC, chanson02 commented on FightSequence.py
> +        Deals damage based on playerAttack vs the targets defensive item.
Does this function actually `deal` the damage, or does it just calculate how much damage the weapon _WOULD DO_ against the opponent

2024-04-06 03:40 UTC, chanson02 commented on FightSequence.py
> +    def __init__(self, player, enemy):
```suggestion
    def __init__(self, player: CharacterFactory.Character, enemy: CharacterFactory.Character):
```

2024-04-06 03:40 UTC, chanson02 commented on FightSequence.py
> +    def Fight(self, playerWeapon, enemyWeapon):
There is some way to make this like `-> tuple[CharacterFactory.Character]` but I don't remember exactly how.

2024-04-06 03:40 UTC, chanson02 commented on dunwoody_disaster/CharacterFactory.py
> +        }
What is the point of this? I have something similar but a little different on my latest branch. Don't want to cause any conflicts.

2024-04-06 03:40 UTC, chanson02 commented on dunwoody_disaster/Item.py
> +    def __init__(self, name, damage, magicCost, staminaCost):
```suggestion
    def __init__(self, name: str, damage: int, magicCost: int, staminaCost: int):
```

2024-04-06 03:40 UTC, chanson02 commented on dunwoody_disaster/Item.py
> +    def __init__(self, name, armorVal):
```suggestion
    def __init__(self, name: str, armorVal: int):
```

2024-04-09 12:56 UTC, MLHumphries commented on dunwoody_disaster/CharacterFactory.py
> +        }
We had talked about putting the meters on the player, so I did that.

2024-04-09 15:48 UTC, chanson02 requested changes
`Mechanical` -> `Stamina` bugs

2024-04-09 15:48 UTC, chanson02 commented on dunwoody_disaster/views/fightScreen.py
> +        curStamina = player.curMechanical
These attributes no longer exist.

2024-04-09 15:48 UTC, chanson02 commented on dunwoody_disaster/views/fightScreen.py
> +        meters["mechanical"].setPercentage(staminaPercentage)
This key no longer exists.

2024-04-09 15:48 UTC, chanson02 commented on dunwoody_disaster/CharacterFactory.py
> +        character.curStamina = data["mechanical"]
We should phase out `data["mechanical"]`. The `CharacterFactory` is going to need some tweaks.

2024-04-09 20:59 UTC, chanson02 commented on dunwoody_disaster/CharacterFactory.py
> +        character.curStamina = data["mechanical"]
I see  that you changed it to use `data['stamina']`, but you also need to change it on `CharacterFactory.class_types`

2024-04-09 21:11 UTC, chanson02 approved these changes
Appears to be working.

2024-04-11 20:26 UTC, instMeyFTW approved these changes

2024-04-11 20:37 UTC, merged